version: '3.3'

services:


  postgres:
    image: postgres:11.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/postgresql/:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U username -d database" ]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.server
    command: [ "/mancala"]
    ports:
      - 80:80
    depends_on:
      - postgres
    links:
      - postgres
    env_file:
      - server/.env
    environment:
      DATABASE_HOST: postgres
    container_name: mancala-server


  react-ui:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"
    container_name: react-ui
    stdin_open: true
    volumes:
      - ./client:/usr/src/app/mancala